In [ ]:
# Create a NumPy array and make a copy of it. Modify the original array and print both
# the original and copied arrays.
import numpy as np
a=np.array([1,2,3,4,5])
b=a.copy()
a[4]=6
print(a)
print(b)

[1 2 3 4 6]
[1 2 3 4 5]


In [ ]:
# 2. Create a view of a NumPy array. Modify the view and print both the original and the
# # view. How do the results compare to using a copy?
import numpy as np
a=np.array([1,2,3,4,5])
b=a.view()
a[4]=6
print(a)
print(b)

[1 2 3 4 6]
[1 2 3 4 6]


In [ ]:
# 3. Explain the difference between array.copy() and array.view() in NumPy. Provide an
# example to illustrate the difference.
a=np.array([1,2,3,4,5])
c=a.copy()
b=a.view()
a[4]=6
print(a)
print(c.base)
print(b.base)

[1 2 3 4 6]
None
[1 2 3 4 6]


In [ ]:
# 4. Create a 2D NumPy array and generate a view that represents only the first row.
# Modify this view and print the changes in both the original array and the view.
a=np.array([[1,2,3],[4,5,6]])
print(a)
print()
b=a.view()
print(b[0])
b[0,1]=9
print()
print(a)
print()
print(b)

[[1 2 3]
 [4 5 6]]

[1 2 3]

[[1 9 3]
 [4 5 6]]

[[1 9 3]
 [4 5 6]]


In [ ]:
# 5. Create a NumPy array and another array by slicing the first array. Check whether the
# second array is a copy or a view of the first array.
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
print()
x=a[2:6]
print(x)
print(x.base)
print(a.base)

[1 2 3 4 5 6 7 8 9]

[3 4 5 6]
[1 2 3 4 5 6 7 8 9]
None


In [ ]:
# 6. Use the np.may_share_memory() function to check if two arrays share the same
# memory. Provide an example.
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
print()
x=a.view()
print(x)
print(np.may_share_memory(a,x)) #if they share returs true otherwise fales

[1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]
True


In [ ]:
# 7. Create a NumPy array, then use the reshape() function on it. Check whether the
# reshaped array is a view or a copy.
a=np.arange(0,6)
print(a)
b=a.reshape(3,2)
print(b)
print(b.base)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [ ]:
# 8. Create a NumPy array and print its shape. Then reshape it to another valid shape and
# print the new shape.
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.shape)
b=a.reshape(3,3)
print()
print(b)
print(b.shape)

(9,)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# 9. Given a 1D array of length 12, reshape it into a 2D array with 3 rows. Then, reshape it
# into a 3D array. Print the shapes at each step.
a=np.arange(0,12).reshape(3,-1)
print(a,a.shape)
b=a.reshape(2,2,-1)
print()
print(b,b.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [ ]:
# 10.Create a 3x4 matrix and then reshape it into a 2x6 matrix. Verify if reshaping changes
# the data content.
a=np.arange(12).reshape(3,4)
print(a,a.shape)
print()
b=a.reshape(2,6)
print(b,b.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [ ]:
# 11.Reshape a 2D array into a 3D array. Then reshape it back to its original 2D shape.
a=np.arange(12).reshape(3,4)
print(a,a.shape)
print()
b=a.reshape(2,2,-1)
print(b,b.shape)
c=b.reshape(3,4)
print()
print(c,c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [ ]:
# 12.Given a 4x4 matrix, reshape it into a 2D array with dimensions 2x8. Then, reshape it
# back to 4x4.
a=np.arange(16).reshape(4,4)
print(a,a.shape)
print()
b=a.reshape(2,8)
print(b,b.shape)
c=b.reshape(4,4)
print()
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]] (2, 8)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# 13.flate 3d array to 1d
a=np.arange(8).reshape(2,2,2)
print(a,a.shape)
print()
b=a.reshape(-1)
print(b,b.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)

[0 1 2 3 4 5 6 7] (8,)


In [ ]:
# 14.Create a 3x3 matrix and iterate over its elements row by row.
a=np.arange(9).reshape(3,3)
for i in a:
  for j in i:
    print(j)

0
1
2
3
4
5
6
7
8


In [ ]:
# 15.Create a 2D array. Print index of each element including that element.
a=np.arange(1,10).reshape(3,3)
for x, i in np.ndenumerate(a):
  print(x,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [ ]:
# 16.Iterate over a 3D array and print each element, along with its corresponding index.
a=np.arange(1,9).reshape(2,2,2)
for x, i in np.ndenumerate(a):
  print(x,i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [ ]:
# 17.Create a 2D NumPy array and use np.nditer() to iterate over it. Print each element.
a=np.arange(1,10).reshape(3,3)
for i in np.nditer(a):
  print(i)

1
2
3
4
5
6
7
8
9


In [2]:
import numpy as np

In [4]:
# 18.Create a 3D array. Print each element and its corresponding index.
a=np.arange(1,9).reshape(2,2,2)
print(a)
print()
for x in np.ndenumerate(a):
  print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 1, 0), 3)
((0, 1, 1), 4)
((1, 0, 0), 5)
((1, 0, 1), 6)
((1, 1, 0), 7)
((1, 1, 1), 8)


In [ ]:
# 19.Create a 6D array and use nditer() and print each element .
a=np.array([1,2,3,4],ndmin=6)
print(a,a.shape)
for i in np.nditer(a):
  print(i)

[[[[[[1 2 3 4]]]]]] (1, 1, 1, 1, 1, 4)
1
2
3
4


In [ ]:
# 20.Create a 2D integer array and use nditer() to iterate over it as if it were an float array.
# Print the elements.
a=np.arange(1,10).reshape(3,3)
for i in np.nditer(a,flags=['buffered'],op_dtypes=[float]):
  print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [5]:
# 21.Use nditer() to iterate over a mixed data type array, where some elements are floats
a=np.array([1,2.1,3,4,5.4,6,7,8.0,9,10])
for i in np.nditer(a,flags=['buffered'],op_dtypes=[float]):
  print(i)

1.0
2.1
3.0
4.0
5.4
6.0
7.0
8.0
9.0
10.0


In [ ]:
# 22.Create a 2D array and iterate over it using nditer() with op_dtypes set to different
# types. Observe and explain the results.
a=np.arange(1,10).reshape(3,3)
for i in np.nditer(a,flags=['buffered'],op_dtypes=[float]):
  print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [ ]:
# 23.Create a 1D array of 10 elements and iterate over it using a step size of 2. Print the
# accessed elements.
a=np.array([1,2,3,4,5,6,7,8,9,10])
for i in np.nditer(a[::2]):
  print(i)

1
3
5
7
9


In [8]:
# 24.Iterate over every second element of a 2D array along with indices of the elements
a=np.arange(1,10).reshape(3,3)
print(a)
print()
for x, i in np.ndenumerate(a[::2]):
  print(x,i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 7
(1, 1) 8
(1, 2) 9


In [9]:
# 25.Create a 3D array and iterate over every second element. Print the elements accessed
# in each step along with indices of element.
a=np.arange(1,9).reshape(2,2,2)
print(a)
print()
for x, i in np.ndenumerate(a[::2]):
  print(x,i)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
